name: OWASP ZAP Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      # --- Paso 1: Checkout del código ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Paso 2: Escaneo OWASP ZAP ---
      - name: Run OWASP ZAP Full Scan
        run: |
          docker run --rm \
            -v $(pwd)/zap-reports:/zap/wrk/ \
            -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py \
            -t "http://${{ secrets.FRONTEND_IP }}" \
            -r /zap/wrk/zap-report.html || true

      # --- Paso 3: Publicar reporte en los logs ---
      - name: Show OWASP ZAP Report
        run: cat zap-report.html || echo "No vulnerabilities found"

      # --- Paso 4: Subir reporte como artefacto a GitHub ---
      - name: Upload OWASP ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-reports/zap-report.html